import sys
from src.graph.state import ResearchState
from src.agents import search_agent, reader_agent, writer_chain, critic_chain
from src.tools import web_search, scrape_url

def call_search_agent(state: ResearchState) -> dict:
    """
    Node 1: Executes the Search Agent to extract web context.
    If the model calls a tool, we intercept it, run it, and store the text.
    """
    print("\n🚀 [Node: Search] Analysing research scope...", flush=True)
    response = search_agent.invoke({"input": f"Find recent, reliable information about: {state['topic']}"})
    
    # Check if the LLM generated tool calls natively
    if hasattr(response, 'tool_calls') and response.tool_calls:
        try:
            # 1. Capture the raw tool arguments generated by Groq
            tool_args = response.tool_calls[0]['args']
            
            # 2. Execute the tool function directly to grab the real text string
            tool_output = web_search.invoke(tool_args)
            
            # 3. Print to console for verification (matching your pipeline debug style)
            print(f"\n--- [Debug] Search Results Generated ---\n{tool_output[:500]}...", flush=True)
            
            # 4. Save the real output text into our state dictionary
            return {"search_results": str(tool_output), "messages": [response]}
        except Exception as e:
            return {"search_results": f"Failed to execute search tool: {str(e)}", "messages": [response]}
        
    return {"search_results": response.content}


def call_reader_agent(state: ResearchState) -> dict:
    """
    Node 2: Selects key candidate URLs and processes them via the deep scraping pipeline.
    """
    print("\n📖 [Node: Reader] Processing top search results...", flush=True)
    
    search_context = state.get("search_results", "No search results available.")
    prompt_input = (
        f"Based on the following search results about '{state['topic']}', "
        f"pick the most relevant URL and scrape it for deeper content.\n\n"
        f"Search Results:\n{search_context}"
    )
    
    response = reader_agent.invoke({"input": prompt_input})
    
    # Check if the LLM generated scraping tool calls natively
    if hasattr(response, 'tool_calls') and response.tool_calls:
        try:
            # 1. Capture tool arguments
            tool_args = response.tool_calls[0]['args']
            
            # 2. Execute the scraper tool directly
            tool_output = scrape_url.invoke(tool_args)
            
            # 3. Print to console for verification
            print(f"\n--- [Debug] Scraped Content Generated ---\n{tool_output[:500]}...", flush=True)
            
            # 4. Save the full page text into our state dictionary
            return {"scraped_content": str(tool_output), "messages": [response]}
        except Exception as e:
            return {"scraped_content": f"Failed to execute scraper tool: {str(e)}", "messages": [response]}
            
    return {"scraped_content": response.content}


def call_writer_chain(state: ResearchState) -> dict:
    """
    Node 3: Formulates or updates the markdown report draft, integrating previous feedback loops.
    """
    print("\n📝 [Node: Writer] Generating or refining the technical research report...", flush=True)
    
    research_combined = (
        f"SEARCH ENGINE HIGHLIGHTS:\n{state.get('search_results', '')}\n\n"
        f"DEEP SCRAPED CONTENT:\n{state.get('scraped_content', '')}"
    )
    
    previous_feedback = state.get("feedback", "No historical feedback. This is the first draft.")
    
    report_markdown = writer_chain.invoke({
        "topic": state['topic'],
        "research": research_combined,
        "feedback": previous_feedback
    })
    
    current_loops = state.get("loop_count", 0)
    return {
        "report": report_markdown, 
        "loop_count": current_loops + 1
    }


def call_critic_chain(state: ResearchState) -> dict:
    """
    Node 4: Evaluates the compiled draft against quality and compliance guidelines.
    """
    print("\n🧐 [Node: Critic] Stress-testing document structure...", flush=True)
    report_to_assess = state.get("report", "Empty draft. Assessment aborted.")
    evaluation_logs = critic_chain.invoke({"report": report_to_assess})
    return {"feedback": evaluation_logs}